### ISSUE TITLE
Build issue with ldc 1.28.1

### ISSUE THREAD

**Issue by carun** [tspike2k/djinnprint#1]
```
$ ldc2 --betterC djinnprint.d examples.d
djinnprint.o:examples.d:function _D8examples11BufferRange3putMFNbNiIAaZv: error: undefined reference to '_d_array_slice_copy'
djinnprint.o:examples.d:function _D10djinnprint8safeCopyFNbNiAaANgaZm: error: undefined reference to '_d_array_slice_copy'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
```

Can you include the build steps or probably `dub.json`?

Works fine with DMD v2.098.1 though.

**Comment by tspike2k** [comment]
Thanks for reporting this issue! I’ve pushed a new commit that tries address this. I’m now able to compile the example file with ldc (version 1.28.0) using the -betterC flag. Please let me know if this fix does the trick.

**Comment by carun** [comment]
Works fine, thanks for the fix so quick.
